version: '2'
services:
  elasticsearch-masters:
    image: justicel/rancher-elasticsearch-conf:v0.5.6
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: elasticsearch-base-master,elasticsearch-datavolume-masters
    volumes_from:
      - elasticsearch-datavolume-masters
  elasticsearch-datavolume-masters:
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      elasticsearch.datanode.config.version: '0'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    volumes:
      - es_masters_data:/usr/share/elasticsearch/data
      - /usr/share/elasticsearch/config
      - /opt/rancher/bin
    entrypoint: /bin/true
    image: docker.elastic.co/elasticsearch/elasticsearch:${es_version}
  elasticsearch-base-master:
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - IPC_LOCK
    environment:
      http.host: 0.0.0.0
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms${java_memory}g -Xmx${java_memory}g"
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      elasticsearch.master.config.version: '0'
      io.rancher.container.hostname_override: container_name
    image: docker.elastic.co/elasticsearch/elasticsearch:${es_version}
    network_mode: container:elasticsearch-masters
    volumes_from:
      - elasticsearch-datavolume-masters
    entrypoint:
      - /opt/rancher/bin/run.sh

  elasticsearch-datanodes:
    image: justicel/rancher-elasticsearch-conf:v0.5.6
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: elasticsearch-base-datanode,elasticsearch-datavolume-datanode
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    volumes_from:
      - elasticsearch-datavolume-datanode
    links:
      - elasticsearch-masters:es-masters
  elasticsearch-datavolume-datanode:
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      elasticsearch.datanode.config.version: '0'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    volumes:
      - es_datanodes_data:/usr/share/elasticsearch/data
      - /usr/share/elasticsearch/config
      - /opt/rancher/bin
    entrypoint: /bin/true
    image: docker.elastic.co/elasticsearch/elasticsearch:${es_version}
  elasticsearch-base-datanode:
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - IPC_LOCK
    environment:
      http.host: 0.0.0.0
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms${java_memory}g -Xmx${java_memory}g"
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      elasticsearch.datanode.config.version: '0'
      io.rancher.container.hostname_override: container_name
    image: docker.elastic.co/elasticsearch/elasticsearch:${es_version}
    volumes_from:
      - elasticsearch-datavolume-datanode
    network_mode: container:elasticsearch-datanodes

  elasticsearch-clients:
    image: justicel/rancher-elasticsearch-conf:v0.5.6
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: elasticsearch-base-clients,elasticsearch-datavolume-clients
    volumes_from:
      - elasticsearch-datavolume-clients
    links:
      - elasticsearch-masters:es-masters
  elasticsearch-datavolume-clients:
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      elasticsearch.datanode.config.version: '0'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    volumes:
      - es_clients_data:/usr/share/elasticsearch/data
      - /usr/share/elasticsearch/config
      - /opt/rancher/bin
    entrypoint: /bin/true
    image: docker.elastic.co/elasticsearch/elasticsearch:${es_version}
  elasticsearch-base-clients:
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - IPC_LOCK
    environment:
      http.host: 0.0.0.0
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms${java_memory}g -Xmx${java_memory}g"
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      elasticsearch.client.config.version: '0'
      io.rancher.container.hostname_override: container_name
    image: docker.elastic.co/elasticsearch/elasticsearch:${es_version}
    volumes_from:
      - elasticsearch-datavolume-clients
    network_mode: container:elasticsearch-clients
    entrypoint:
      - /opt/rancher/bin/run.sh

  kopf:
    image: rancher/kopf:v0.4.0
    ports:
      - "${kopf_port}:80"
    environment:
      KOPF_SERVER_NAME: 'es.dev'
      KOPF_ES_SERVERS: 'es-clients:9200'
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
    links:
      - elasticsearch-clients:es-clients
volumes:
  es_datanodes_data:
    driver: rancher-ebs
    per_container: true
    driver_opts:
      size: ${storage_size}
      volumeType: gp2
  es_masters_data:
    driver: rancher-ebs
    per_container: true
    driver_opts:
      size: 20
      volumeType: gp2
  es_clients_data:
    driver: rancher-ebs
    per_container: true
    driver_opts:
      size: 20
      volumeType: gp2
